version: '2'

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - "/home/deploy/projects/${PROJECT_NAME}:/var/www/html/wp-content/themes/${PROJECT_NAME}"
    ports:
      - "${NEXT_PORT}:80"
    expose:
      - "${NEXT_PORT}"
    restart: always
    external_links:
      - mysql:db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: spaces
      WORDPRESS_DB_PASSWORD: zah0Eegh
      WORDPRESS_DB_NAME: "${PROJECT_NAME}"
      VIRTUAL_HOST: "${PROJECT_NAME}.lab.spaceshiplabs.com"
    network_mode: bridge
