<script src="<?=get_bloginfo('template_directory')?>/bower_components/angular/angular.min.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/bower_components/hammer.js/hammer.min.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/bower_components/angular-aria/angular-aria.min.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/bower_components/angular-animate/angular-animate.min.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/bower_components/angular-material/angular-material.min.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/bower_components/jquery/dist/jquery.min.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/bower_components/angularjs-mongolab/src/angular-mongolab.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/bower_components/angularUtils-pagination/dirPagination.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/js/fastclick.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/js/modernizr.custom.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/js/owl.carousel.min.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/js/app.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/js/factories.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/js/config.js"></script>
<script src="http://maps.google.com/maps/api/js?v=3" type="text/javascript"></script>
<script src="<?=get_bloginfo('template_directory')?>/js/controllers/headerController.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/bower_components/wow/dist/wow.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="http://code.highcharts.com/maps/modules/map.js"></script>
<script src="https://code.highcharts.com/maps/modules/data.js"></script>
<script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
<script src="https://code.highcharts.com/mapdata/countries/mx/mx-all.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
<script src="<?=get_bloginfo('template_directory')?>/js/funciones.js"></script>